### PR TITLE
use createDerived from nanostores

### PR DESCRIPTION
**Pull request by Guria**
not sure I am doing right thing, but worth to try :)

### CODE REVIEW

**Comment by Guria** [comment]
@ai does it makes sense?

**Comment by ai** [comment]
Sorry. Had no time to look yet.

**Comment by ai** [comment]
Looks good! I wrote this block before I finished Nano Stores, so it was out of current Nano Store philosophy.

Just a small question: why do we need `as const` in `Map`?

**Comment by Guria** [comment]
@ai 
image
It might not needed in this task, but it enables more sctrict inferring.

We will get ` Set<"start" | "signin">` instead of ` Set<string>`

**Pull request merged**
