### PR TITLE
Fixed small typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by uuladzislau**
I noticed a small typo on screenshot of `CONTRIBUTING.md` file shared in one of Andrei's recent tweets, and it bothered me so much, so I went ahead and submitted a PR to correct it.

I didn't run any tests because I am 100% sure this change won't break anything. However, please let me know if you would still like me to perform the standard set of tests and checks on the project.

### CODE REVIEW

**Comment by ai** [comment]
Thanks!

**Comment by ai** [comment]
Oops https://github.com/hplush/slowreader/actions/runs/9150418099/job/25155165983

Can you fix links too?

**Comment by uuladzislau** [comment]
Uno momento

**Comment by uuladzislau** [comment]
@ai I've fixed references in #213, the test is green. Also searched for references throughout the codebase, seems like the table of content was the only place.

**Pull request merged**
